### ISSUE TITLE
Deprecated function

### ISSUE THREAD

**Issue by jaredatch** [jaredatch/Basic-User-Avatars#19]
https://wordpress.org/support/topic/suggestions-for-next-update-2?replies=2#post-8396370

**Comment by andrewlimaza** [comment]
Summarizing the ticket here:

1. get_users_of_blog at line 467: Use get_users()
2. create_function at line 285: Potential risk: Low. Create an anonymous (lambda-style) function. A native anonymous function should be used instead.
3. create_function at line 288: Potential risk: Low. Create an anonymous (lambda-style) function. A native anonymous function should be used instead.

**Comment by andrewlimaza** [comment]
This has been fixed and should go out in next release.
