### ISSUE TITLE
shortcode not working in form-edit-account.php

### ISSUE THREAD

**Issue by tmartin007** [jaredatch/Basic-User-Avatars#22]
Hi Jared,

thanks for the nice plugin. - I was trying to use it in a customized "form-edit-account.php" to let users upload local avatars right from their "My Account" profile page. - While the shortcode [basic-user-avatars] works fine on a dedicated WP page, it fails to upload any selected image to the user's meta-data. - However, you can "nuke" any avatar image that might have been uploaded otherwise.  - It would be very nice, if you could give hints that solve the problem. - Here is my code-snipppet form the form-edit-account.php. 

```
<!-- (BEGIN) AVATAR selector -->
<table class="form-row-last">
<td style="border-bottom: 0; ">[basic-user-avatars]</td>

</table>
<!-- (END) AVATAR selector -->

```

On a second (unrelated) note, it would be very nice, if the selected avatar image could be previewed before uploading it. - Do you have an idea, how this can be accomplished ? I usually do C++ etc and I'm not really a html/css/php programmer, so it is not obvious to me ...

For your efforts, thank you very much in advance.

Best regards,

-Thomas

**Comment by jenessawhite** [comment]
@tmartin007 did you ever figure out to make this work with what I'm assuming you were using was Woocommerce?

**Comment by andrewlimaza** [comment]
Are you still experiencing this issue @tmartin007?

**Comment by andrewlimaza** [comment]
Please feel free to open a new ticket with debug information if you still experience this issue.
