### ISSUE TITLE
Heading level incorrect

### ISSUE THREAD

**Issue by lutrov** [jaredatch/Basic-User-Avatars#25]
Wordpress have changed heading level hierarchy back in V4.4, so instead of:

	`<h3><?php _e( 'Avatar', 'basic-user-avatars' ); ?></h3>`

it should be:

	`<h2><?php _e( 'Avatar', 'basic-user-avatars' ); ?></h2>`

**Comment by andrewlimaza** [comment]
Thanks for this, this has been fixed and should be out in the near future.
