### ISSUE TITLE
how admin can update user meta using gravity forms

### ISSUE THREAD

**Issue by ookdevil** [jaredatch/Basic-User-Avatars#32]
Hi Guys,

I am using **Gravity Formas user registration addon** I can update user meta of the logged-in user only but  I want also to update user meta whenever admin fills a form by entering user Email in the Email field.
Whenever Admin fills a form and enters email id which is users' email and all the populated fields should be updated to the user holding the Email.

Please give a golden or suggest a plugin
Thanks 
Aman Kumar Shah

**Comment by andrewlimaza** [comment]
Hi @ookdevil 

Thanks for reaching out, please note that this repo isn't used for support questions but bug tracking/reporting.

This sounds like you would need to reach out to the Gravity Forms support team to assist you with their plugin.

Thank you for understanding.
