### ISSUE TITLE
Feature request: custom prefix for filenames

### ISSUE THREAD

**Issue by Beee4life** [jaredatch/Basic-User-Avatars#7]
I prefer to have the $user_displayname prefixed with avatar_ instead of suffixed.
I hardcoded it myself by changing line 446 from 
`$name = $base_name = sanitize_file_name( $user->display_name . '_avatar' );`
to
`$name = $base_name = 'avatar_' . sanitize_file_name( $user->display_name );`
but like to see an option for it which is update proof.

**Comment by jaredatch** [comment]
Sure, I'll make this filterable in the next release when I get time.

**Comment by Beee4life** [comment]
Also a custom upload directory would be awesome... i think that's even more important.
with 2000+ members i don't want the avatars in between the site's normal uploads.

The prefix is only a temp solution to filter avatars better but if it's a custom dir, there's not much need for it imo.

**Comment by jaredatch** [comment]
Agreed, thanks more useful and practical.

Will take a look at it via http://wordpress.stackexchange.com/questions/67763/how-to-change-upload-directory-in-wp-handle-upload when I have time.

**Comment by Beee4life** [comment]
Hey @jaredatch was just looking through old issues, when I came across this. Has been open for 2 years already... Any plans on reviving/updating the plugin ? Would like to keep on using it...

**Comment by Beee4life** [comment]
Dropped this plugin... so topic is moot.
